#TODO test and dump config
# Note/TODO: This can take properties from maven
spring:
  profiles:
    group:
      default:
        # Default to prod (prod-first / secure by default)
        # Docs say last applied property wins; if another profile is activated,
        #  it overrides the individual db config attributes.
        - prod
      prod:
        - postgres
        - testdata # Runs DbInitializer conditionally
      dev:
        - circular
        # TODO TBH you should be developing as close to prod as possible so this should also be postgres?
        - h2db-dev
        - debug
        - testdata # Runs DbInitializer conditionally
      ci:
        # postgres  #TODO somethings funky with overriding the ddl-auto type
        - integration-tests
        - h2db-dev # Spec says use in-memory db, so we use h2, but default to file-backed so we can inspect the database with tooling.
        - h2db-integration
        #- h2db-mem
        #- debug-sql
        #- parallel-tests # pointless, the test are a trivial amount of time to run. its bloody spring startup that takes 30 seconds to start
        #- lazy-init  # doesnt improve startup at all (expected since most of it seems to be db related)
      debug:
        - debug-sql
      debug-max:
        - verbose-max
        - debug-sql
---
### From here it's profile components that are composed above
spring:
  config.activate.on-profile: h2db-dev
  datasource:
    # Use a file-backed H2 database so that we can inspect it with the intellij DB tools
    # TODO the correct way to use a path would be to use a runtime path relative to the JAR or such
    #   (also, this solution ties it strongly to maven?)
    # TODO have it log the URL to the console
    #TODO we override the builtin alias for time to mock time, there is probably a better way to do this
    #TODO/security note this leaks data into the product jar
    url: jdbc:h2:file:@project.build.directory@/cinema;AUTO_SERVER=TRUE;BUILTIN_ALIAS_OVERRIDE=TRUE
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
---
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:9001/cinema
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config.activate.on-profile: integration-tests
  #TODO why do we set this for integration tests?
  shell.interactive.enabled: true #TODO why the hell do we keep turning this off
---
spring:
  config.activate.on-profile: h2db-integration
  #Try to make tests a little more robust to accidentally leaving the database on the file path running somewhere
  # by putting it on a different path
  datasource:
    url: jdbc:h2:file:@project.build.directory@/cinema-test;AUTO_SERVER=TRUE;BUILTIN_ALIAS_OVERRIDE=TRUE
---
spring:
  config.activate.on-profile: verbose-max
logging.level.root: DEBUG
logging.level.sun.rmi.loader: INFO
logging.level.sun.rmi.transport.tcp: INFO
logging.level.javax.management.remote.rmi: INFO
---
spring:
  config.activate.on-profile: verbose-trace # so loud
logging.level.root: DEBUG
---
spring:
  config.activate.on-profile: debug-sql
  jpa:
    # From: https://github.com/amigoscode/spring-data-jpa-course/blob/main/src/main/resources/application.properties
    show-sql: true
    properties.hibernate.format_sql: true #TODO check this works
# Enable showing bound parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
---
#TODO spring hella slw but its probablz mz machine being overloaded
spring:
  config.activate.on-profile: parallel-test
cucumber.execution.parallel.enabled: true
#hibernate.temp.use_jdbc_metadata_defaults: false
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
# spring.data.jpa.repositories.bootstrap-mode: DEFERRED
---
spring:
  config.activate.on-profile: lazy-init
  main.lazy-initialization: true
---
spring:
  config.activate.on-profile: h2db-mem
  datasource:
    url: jdbc:h2:mem:cinema
---
spring:
  config.activate.on-profile: circular #TODO probably a baaaad idea, couldnt deal with the inter-service object translation dependencies in another way right now
  main:
    allow-circular-references: true
---
spring:
  config.activate.on-profile: livereload
  jpa:
    hibernate.ddl-auto: update
